name: recorded
description: Hierarchical mapping from recorded uHumans2 class-ID images
scene_structure: hierarchical
semantics:
  source: recorded
  labelspace_config: spark_3dsg_pipeline:config/labelspaces/uhumans2_office.yaml
  pipeline_config: spark_3dsg_pipeline:config/labelspaces/uhumans2_remap.yaml
visualization: {profile: hierarchical}
hydra_config: uhumans2.yaml
